---
title: "IFdosingStats - 10 trial blocks - beginning, middle, end"
output: html_document
usage: You must make sure the Rdata files from "interferenceDosing_stats.R" have been sucessfully run, and that the stats files are in the "R output files" folder on the drive. Make sure you have set blocksize = 10
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(ez)
library(tidyverse)
library(afex)
# #setwd("/Volumes/mnl/Data/Adaptation/interference_dosing/R output files/10 trial blocks") # Mac
# setwd("Z:\\Data\\Adaptation\\interference_dosing\\R output files\\10 trial blocks") # PC
# load(file = "lhKinematics_stats.Rdata")
# load(file = "rhKinematics_stats.Rdata")
# #setwd("/Volumes/mnl/Data/Adaptation/interference_dosing/R output files") # Mac
# setwd("Z:\\Data\\Adaptation\\interference_dosing\\R output files") # PC
# load(file = "FC_stats.Rdata")
# load(file = "FC_3way.Rdata")
# load(file = "hand_diff_stats.Rdata")
```

# Exposure Phases
## Left hand
### IDE
```{r, }
# RM.ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(5,12,18)), dv = ide.bc, within = block, between = group, wid = subjectID, detailed = TRUE)
## Beginning one-way ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(5)), dv = ide.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(5)), dv = ide.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
## Mid one-way ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(12)), dv = ide.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(12)), dv = ide.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
## End one-way ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(18)), dv = ide.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(18)), dv = ide.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
```

### EPX
```{r,}
## RM.ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(5,12,18)), dv = EP_X.bc, within = block, between = group, wid = subjectID, detailed = TRUE)
## Beginning one-way ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(5)), dv = EP_X.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(5)), dv = EP_X.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
## Mid one-way ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(12)), dv = EP_X.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(12)), dv = EP_X.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
## End one-way ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(18)), dv = EP_X.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(18)), dv = EP_X.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
```

## Right Hand
### IDE
```{r, }
# RM.ANOVA
ezANOVA(subset(rhKinematics_stats, block %in% c(5,12,18)), dv = ide.bc, within = block, between = group, wid = subjectID, detailed = TRUE)
t.test(subset(rhKinematics_stats$ide.bc, block %in% c(5), mu = 0))
```


# Post-Exposure Phases
## Left hand
### IDE
```{r, }
# RM.ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(19,22)), dv = ide.bc, within = block, between = group, wid = subjectID)
ezANOVA(subset(lhKinematics_stats, block %in% c(18,19)), dv = ide.bc, within = block, between = group, wid = subjectID)
ezANOVA(subset(lhKinematics_stats, block %in% c(19)), dv = ide.bc, between = group, wid = subjectID)

ezANOVA(subset(lhKinematics_stats, block %in% c(19)), dv = ide.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(19)), dv = ide.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
```

### EPX
```{r, }
# RM.ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(19,22)), dv = EP_X.bc, within = block, between = group, wid = subjectID)

ezANOVA(subset(lhKinematics_stats, block %in% c(19)), dv = EP_X.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(19)), dv = EP_X.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)

t.test(subset(lhKinematics_stats, group == 2 & block == 19)$EP_X, subset(lhKinematics_stats, group == 2 & block == 22)$EP_X, paired = TRUE)
```

## Right Hand
### IDE
```{r, }
# RM.ANOVA NOTE: this is a 1-way ANOVA using only the first block of post-exposure.
ezANOVA(subset(rhKinematics_stats, block %in% c(22)), dv = ide.bc, between = group, wid = subjectID)
```

# Force Channel Data
## Kin Baseline
```{r, }
# RM.ANOVA
ezANOVA(subset(FC_stats, sample %in% c(50,950)), dv = kbmean, within = sample, between = group, wid = subID)
```
## Block 1
```{r, }
# RM.ANOVA
ezANOVA(subset(FC_stats, sample %in% c(50,950)), dv = bk1mean, within = sample, between = group, wid = subID)
```
## Block 2
```{r, }
# RM.ANOVA
ezANOVA(subset(FC_stats, sample %in% c(50,950)), dv = bk2mean, within = sample, between = group, wid = subID)
```
## Block 3
```{r, }
# RM.ANOVA
ezANOVA(subset(FC_stats, sample %in% c(50,950)), dv = bk3mean, within = sample, between = group, wid = subID)
```
## 3-way ANOVA
```{r, }
# 3-way RM.ANOVA
 
temp = ezANOVA(subset(FC_3way.ex, sample %in% 950), dv = value, between = group, wid = subID, return_aov = TRUE)
TukeyHSD(temp$aov)

# EXPERIMENT 2 ONLY
# t.test for Extent main effect
t.test(subset(FC_3way.ex, sample %in% 50)$value, subset(FC_3way.ex, sample %in% 950)$value, paired = TRUE)

t.test(subset(FC_3way.ex, sample %in% 50 & phase %in% 'bk1mean')$value, mu = 0) # first 6 trials, early
t.test(subset(FC_3way.ex, sample %in% 50 & phase %in% 'bk2mean')$value, mu = 0) # middle 6 trials, early
t.test(subset(FC_3way.ex, sample %in% 50 & phase %in% 'bk3mean')$value, mu = 0) # last 6 trials, early

t.test(subset(FC_3way.ex, sample %in% 950 & phase %in% 'bk1mean')$value, mu = 0) # first 6 trials, early
t.test(subset(FC_3way.ex, sample %in% 950 & phase %in% 'bk2mean')$value, mu = 0) # middle 6 trials, early
t.test(subset(FC_3way.ex, sample %in% 950 & phase %in% 'bk3mean')$value, mu = 0) # last 6 trials, early


##### Post-hoc test for Extent X Time interaction (in the manuscript I use Time instead of phase)
# phase 1 t.test
t.test(subset(FC_3way.ex, sample %in% 50 & phase %in% 'bk1mean')$value, subset(FC_3way.ex, sample %in% 950 & phase %in% 'bk1mean')$value, paired = TRUE)

# phase 2 t.test
t.test(subset(FC_3way.ex, sample %in% 50 & phase %in% 'bk2mean')$value, subset(FC_3way.ex, sample %in% 950 & phase %in% 'bk2mean')$value, paired = TRUE)

# phase 3 t.test
t.test(subset(FC_3way.ex, sample %in% 50 & phase %in% 'bk3mean')$value, subset(FC_3way.ex, sample %in% 950 & phase %in% 'bk3mean')$value, paired = TRUE)
```

# LFvp.bc Data
## Exposure
```{r, }
# RM.ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(5,12,18)), dv = LFvp.bc, within = block, between = group, wid = subjectID, detailed = TRUE)
# Beginning one-way ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(5)), dv = LFvp.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(5)), dv = LFvp.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
# Mid one-way ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(12)), dv = LFvp.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(12)), dv = LFvp.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
# End one-way ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(18)), dv = LFvp.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(18)), dv = LFvp.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
```

## Post-Exposure
```{r, }
# RM.ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(19,22)), dv = LFvp.bc, within = block, between = group, wid = subjectID)

ezANOVA(subset(lhKinematics_stats, block %in% c(19)), dv = LFvp.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(19)), dv = LFvp.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
```

# LFoff.bc Data
## Exposure
```{r, }
# RM.ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(5,12,18)), dv = LFoff.bc, within = block, between = group, wid = subjectID, detailed = TRUE)
# Beginning one-way ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(5)), dv = LFoff.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(5)), dv = LFoff.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
# Mid one-way ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(12)), dv = LFoff.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(12)), dv = LFoff.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
# End one-way ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(18)), dv = LFoff.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(18)), dv = LFoff.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)
```

## Post-Exposure
```{r, }
# RM.ANOVA
ezANOVA(subset(lhKinematics_stats, block %in% c(19,22)), dv = LFoff.bc, within = block, between = group, wid = subjectID)

ezANOVA(subset(lhKinematics_stats, block %in% c(19)), dv = LFoff.bc, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(19)), dv = LFoff.bc, between = group, wid = subjectID, return_aov = TRUE)
TukeyHSD(temp$aov)

t.test(subset(lhKinematics_stats, group == 1 & block == 19)$LFoff.bc, subset(lhKinematics_stats, group == 1 & block == 22)$LFoff.bc, paired = TRUE)
```

## Hand Timing
```{r}
# LH Reaction Time, kb->ex
ezANOVA(subset(lhKinematics_stats, block %in% c(4,5)), dv = RT_c, within = block, between = group, wid = subjectID)
```

```{r}
# RH Reaction Time, kb->ex
ezANOVA(subset(rhKinematics_stats, block %in% c(4,5)), dv = RT_c, within = block, between = group, wid = subjectID)
temp = ezANOVA(subset(rhKinematics_stats, block %in% c(4,5)), dv = RT_c, between = group, wid = subjectID, return_aov = T)
TukeyHSD(temp$aov)
t.test(subset(rhKinematics_stats, block %in% 5)$RT_c, subset(rhKinematics_stats, block %in% 4)$RT_c, paired = TRUE)
```

```{r}
# LH velPeakTime, kb->ex
ezANOVA(subset(lhKinematics_stats, block %in% c(4,5)), dv = velPeakTime_c, within = block, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(4,5)), dv = velPeakTime_c, between = group, wid = subjectID, return_aov = T)
TukeyHSD(temp$aov)
t.test(subset(lhKinematics_stats, block %in% 5)$velPeakTime_c, subset(lhKinematics_stats, block %in% 4)$velPeakTime_c, paired = TRUE)
```

```{r}
# RH velPeakTime, kb->ex
ezANOVA(subset(rhKinematics_stats, block %in% c(4,5)), dv = velPeakTime_c, within = block, between = group, wid = subjectID)
temp = ezANOVA(subset(rhKinematics_stats, block %in% c(4,5)), dv = velPeakTime_c, between = group, wid = subjectID, return_aov = T)
TukeyHSD(temp$aov)
t.test(subset(rhKinematics_stats, block %in% 5)$velPeakTime_c, subset(rhKinematics_stats, block %in% 4)$velPeakTime_c, paired = TRUE)
```

```{r}
# LH MT, kb->ex
ezANOVA(subset(lhKinematics_stats, block %in% c(4,5)), dv = MT_c, within = block, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(4,5)), dv = MT_c, between = group, wid = subjectID, return_aov = T)
TukeyHSD(temp$aov)
t.test(subset(lhKinematics_stats, block %in% 5)$MT_c, subset(lhKinematics_stats, block %in% 4)$MT_c, paired = TRUE)
```

```{r}
# RH MT, kb->ex
ezANOVA(subset(rhKinematics_stats, block %in% c(4,5)), dv = MT_c, within = block, between = group, wid = subjectID)
temp = ezANOVA(subset(rhKinematics_stats, block %in% c(4,5)), dv = MT_c, between = group, wid = subjectID, return_aov = T)
TukeyHSD(temp$aov)
t.test(subset(rhKinematics_stats, block %in% 5)$MT_c, subset(rhKinematics_stats, block %in% 4)$MT_c, paired = TRUE)
```

```{r}
# LH mov_int, kb->ex
ezANOVA(subset(lhKinematics_stats, block %in% c(4,5)), dv = mov_int_c, within = block, between = group, wid = subjectID)
temp = ezANOVA(subset(lhKinematics_stats, block %in% c(4,5)), dv = mov_int_c, between = group, wid = subjectID, return_aov = T)
TukeyHSD(temp$aov)
t.test(subset(lhKinematics_stats, block %in% 5)$mov_int_c, subset(lhKinematics_stats, block %in% 4)$mov_int_c, paired = TRUE)
```

```{r}
# RH mov_int, kb->ex
ezANOVA(subset(rhKinematics_stats, block %in% c(4,5)), dv = mov_int_c, within = block, between = group, wid = subjectID)
temp = ezANOVA(subset(rhKinematics_stats, block %in% c(4,5)), dv = mov_int_c, between = group, wid = subjectID, return_aov = T)
TukeyHSD(temp$aov)
t.test(subset(rhKinematics_stats$mov_int_c, block %in% 4), subset(rhKinematics_stats$mov_int_c, block %in% 5), paired = TRUE)
```

```{r}
# Hand diff onset lag, kb->ex
ezANOVA(subset(hand_diff_stats, block %in% c(4,5)), dv = lag, within = block, between = group, wid = subjectID)
t.test(subset(hand_diff_stats, block %in% 4)$lag, subset(hand_diff_stats, block %in% 5)$lag, paired = T)
t.test(subset(hand_diff_stats, block %in% 4)$lag, alternative = "greater", mu = 0)
t.test(subset(hand_diff_stats, block %in% 5)$lag, alternative = "less", mu = 0)

```

```{r}
# Hand diff velPeakTime, kb->ex
ezANOVA(subset(hand_diff_stats, block %in% c(4,5)), dv = velPeakTime, within = block, between = group, wid = subjectID)

t.test(subset(hand_diff_stats, block %in% 4)$velPeakTime, alternative = "less", mu = 0)
t.test(subset(hand_diff_stats, block %in% 5)$velPeakTime, alternative = "greater", mu = 0)

```

```{r}
# Hand diff lagf, kb->ex
ezANOVA(subset(hand_diff_stats, block %in% c(4,5)), dv = lagf, within = block, between = group, wid = subjectID)

t.test(subset(hand_diff_stats, block %in% 4)$lagf, alternative = "less", mu = 0)
t.test(subset(hand_diff_stats, block %in% 5)$lagf, alternative = "greater", mu = 0)
```

```{r Q-Q plots}
ggplot(data = subset(lhKinematics_stats, block %in% c(5,12,18)), aes(sample = ide.bc))+stat_qq()+stat_qq_line()
ggplot(data = subset(lhKinematics_stats, block %in% c(5,12,18)), aes(sample = EP_X.bc))+stat_qq()+stat_qq_line()
ggplot(data = subset(lhKinematics_stats, block %in% c(5,12,18)), aes(sample = LFvp.bc))+stat_qq()+stat_qq_line()
ggplot(data = subset(lhKinematics_stats, block %in% c(5,12,18)), aes(sample = LFoff.bc))+stat_qq()+stat_qq_line()
```

```{r Shapiro-Wilk Normality Tests}
# mod.lh_ide.afex = aov_ez(subset(lhKinematics_stats, block %in% c(5,12,18)), dv = "ide.bc", within = "block", between = "group", id = "subjectID", type = "III")
# shapiro.test(residuals(mod.lh_ide.afex))
# 
# mod.lh_EP_X.afex = aov_ez(subset(lhKinematics_stats, block %in% c(5,12,18)), dv = "EP_X.bc", within = "block", between = "group", id = "subjectID", type = "III")
# shapiro.test(residuals(mod.lh_EP_X.afex))
# 
# mod.lh_LFvp.afex = aov_ez(subset(lhKinematics_stats, block %in% c(5,12,18)), dv = "LFvp.bc", within = "block", between = "group", id = "subjectID", type = "III")
# shapiro.test(residuals(mod.lh_LFvp.afex))
# 
# mod.lh_LFoff.afex = aov_ez(subset(lhKinematics_stats, block %in% c(5,12,18)), dv = "LFoff.bc", within = "block", between = "group", id = "subjectID", type = "III")
# shapiro.test(residuals(mod.lh_LFoff.afex))

# res.afex = cbind(matrix(residuals(mod.lh_ide.afex), ncol=1),
#                  matrix(residuals(mod.lh_EP_X.afex), ncol=1),
#                  matrix(residuals(mod.lh_LFvp.afex), ncol=1),
#                  matrix(residuals(mod.lh_LFoff.afex), ncol=1))
# res.afex = as.data.frame(res.afex, col.names = c("ide.bc", "EP_X.bc", "LFvp.bc", "LFoff.bc"))

## Shapiro-WIlks test on last block of exposure...when things should be settled in (no effect for time)
# This must be carried out for each group individually according to Vickers 2005 (quote from Altman 1991)
## Experiment 1
# shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 1)$ide.bc)
# shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 2)$ide.bc)
# shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 3)$ide.bc)
# 
# shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 1)$EP_X.bc)
# shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 2)$EP_X.bc)
# shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 3)$EP_X.bc)
# 
# shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 1)$LFvp.bc)
# shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 2)$LFvp.bc)
# shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 3)$LFvp.bc)
# 
# shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 1)$LFoff.bc)
# shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 2)$LFoff.bc)
# shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 3)$LFoff.bc)

## Experiment 2
shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 4)$ide.bc)
shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 5)$ide.bc)
shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 6)$ide.bc)

shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 4)$EP_X.bc)
shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 5)$EP_X.bc)
shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 6)$EP_X.bc)

shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 4)$LFvp.bc)
shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 5)$LFvp.bc)
shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 6)$LFvp.bc)

shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 4)$LFoff.bc)
shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 5)$LFoff.bc)
shapiro.test(subset(lhKinematics_stats, block %in% c(18) & group == 6)$LFoff.bc)
```

```{r Non-parametric ANOVAs}
# Permutation tests (Non-parametric ANOVA for mixed method. NOTE only verified for main effects. Dont trust the interactions)
# These work for either experiment
ezPerm(subset(lhKinematics_stats, block %in% c(5,12,18)), dv = ide.bc, within = block, between = group, wid = subjectID)
ezPerm(subset(lhKinematics_stats, block %in% c(5,12,18)), dv = EP_X.bc, within = block, between = group, wid = subjectID)
ezPerm(subset(lhKinematics_stats, block %in% c(5,12,18)), dv = LFvp.bc, within = block, between = group, wid = subjectID)
ezPerm(subset(lhKinematics_stats, block %in% c(5,12,18)), dv = LFoff.bc, within = block, between = group, wid = subjectID)
```

